language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
script:
  - ./gradlew build && ./gradlew test
after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/vmiklos/plees-tracker/master/tools/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^ci/' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=vmiklos/plees-tracker /tmp/travis-automerge"
env:
  global:
    secure: cULT71O65ZhEf/+4wguvtkKZbiCdpOQtO01YnJRG2xKyfayJcXGPhWm/sRqSsDBq33Z/JYar2mWK3W7DVN3I8Kw26MKJ5c+p61XQXw6wi8L/LC4e8ZQR/zvzLdSk8nrScWG9DJBW5kEKlkX6zbCqPIXA1RI0MaWWV0Nj/QFhwRJvkMpzpGBvzzNCHTaoajcMYvFoYMZgqOlIK+IlBJfDyq8pPf2Yo+HVlIaZN8pn+b8TrbbRlU6XLXJJczIo7FYJvQkGtC20FeOPgo7z+nBoh3n4UTqsNwsij1jVOi1xUDCcBMNdq3lCUI18/WjCzvuZFzOeJrtM67CyGmL0k+7UsxSRpb4M6gSPlzSd1WHHX3+oQi2OKBqS5emCVxhRfG5AH8EjWM+TVkThLolDXskju1YZnzu3ATz9K2tql6j9lPoc9av3A0GfQ9BiGHzkBEoaam4YZeD1pJ8CPu4er64zntMxG1icS6sO/LFtSrBzRYRL8sbWp67GmZvFVoGbaqtSz3Fh2HTQ8jursNyiNB+KsbjDjj/LiVaycRHFmspHiUrdP2vOdq+FnCGubb9dHzeIsxr1OAG2kSYQ/u0QyN3+Imy3js8Lkkbv/oKT4Rp3OzGK+kNog5DL1oEXF0vSQZ0yVl4KSg1J4Ce/9r3dYc2xJmaXahuPLedk/KpPFlPLpQs=
